### PR TITLE
made ocean token pausable

### PR DESCRIPTION
**Pull request by H34D**

### CODE REVIEW

**Comment by aabdulwahed** [comment]
can you rebase the code to master ?

**Comment by H34D** [comment]
> can you rebase the PR to master ?

nope

**Comment by aabdulwahed** [comment]
> > can you rebase the PR to master ?

> nope

So what is the difference ? Is that meant to be for testing on rinkeby ?

**Comment by H34D** [comment]
> So what is the difference ? Is that meant to be for testing on rinkeby ?

yes, all testing is done on rinkeby right now

**Comment by H34D** [comment]
It's easy, only 1 file to review here: https://github.com/oceanprotocol/ocean-token/pull/4

**Pull request merged**
